### PR TITLE
Add WA join confirmation keybind

### LINKED ISSUE #42: Add keybind for joining WA
Breeze++ never had this, but I think a keybind to confirm joining the World Assembly would be nice and help make switching more ergonomic.

### PR DESCRIPTION
**Pull request by esfalsa**
Closes #42 

I've mapped the default to <kbd>Enter</kbd>; I'm not sure if there's some existing default from another tool that people would be used to.

### CODE REVIEW

**Comment by paulhaku** [comment]
Works fine, but I'm unsure about it being a different key from resign. Personally, it feels more natural to me to use the same key for resigning and admitting, but we could ask for feedback about this.

**Review by paulhaku — APPROVED** [review]
Maybe merge functionality with resigning?

**Comment by esfalsa** [comment]
Yeah, I could see that — we can see what the feedback looks like.

**Comment by esfalsa** [comment]
I think the feedback we got swayed towards using the same key, so I've gone ahead and changed that to be the case.

**Review by paulhaku — APPROVED** [review]

**Pull request merged**
